modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
	modId="jmc"
	version="2.0"
	displayName="Just More Cake!"
	updateJSONURL="http://myurl.me/"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/just-more-cakes"
	logoFile="pack.png"
	credits="Me the mod author"
	authors="MincraftEinstein"
	description='''
A mod that adds 30+ new cakes to Minecraft. Some with special properties, some with no properties and some with useless properties. Chocolate Cake, Triple Decker Cake, TNT Cake...
'''

[[dependencies.jmc]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jmc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.jmc]]
    modId="einsteins_library"
    mandatory=true
    versionRange="[1.4,)"
    ordering="NONE"
    side="BOTH"
