modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
#issueTrackerURL="http://my.issue.tracker/"

[[mods]]
	modId="jmc"
	version="4.1"
	displayName="Just More Cakes!"
	#updateJSONURL="http://myurl.me/"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/just-more-cakes"
	logoFile="logo.png"
	credits="Me the mod author"
	authors="MincraftEinstein"
	description='''
A mod that adds 30+ new cakes to Minecraft. Some with special properties, some with no properties and some with useless properties. Chocolate Cake, Three Tiered Cake, TNT Cake...
'''

[modproperties.jmc]
    catalogueItemIcon="jmc:chocolate_cake"
    configuredBackground="minecraft:textures/block/bricks.png"

[[dependencies.jmc]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.98,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jmc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19, 1.20]"
    ordering="NONE"
    side="BOTH"
