modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
#issueTrackerURL="http://my.issue.tracker/"

[[mods]]
	modId="jmc"
	version="3.0"
	displayName="Just More Cakes!"
	#updateJSONURL="http://myurl.me/"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/just-more-cakes"
	logoFile="pack.png"
	credits="Me the mod author"
	authors="MincraftEinstein"
	itemIcon="jmc:chocolate_cake" #Used by Catalogue
	description='''
A mod that adds 30+ new cakes to Minecraft. Some with special properties, some with no properties and some with useless properties. Chocolate Cake, Three Tiered Cake, TNT Cake...
'''

[[dependencies.jmc]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jmc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17]"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.jmc]]
    modId="einsteins_library"
    mandatory=true
    versionRange="[2.0,)"
    ordering="NONE"
    side="BOTH"
